sudo: required
dist: trusty

services:
  - docker

env:
  global:
    - DOCKER_VERSION=1.10.3-0~trusty

before_install:
  # List available docker versions.
  - apt-cache madison docker-engine
  # Update Docker to needed version https://graysonkoonce.com/managing-docker-and-docker-compose-versions-on-travis-ci/.
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}

matrix:
  include:
    - env:
      - TAG=inspirehep/python-base:2.7
      - DOCKERFILE=python_base/Dockerfile 
      - ARGS='--build-arg INSPIRE_PYTHON_VERSION=2.7'
    - env:
      - TAG=inspirehep/python-base:latest
      - DOCKERFILE=python_base/Dockerfile 
      - ARGS='--build-arg INSPIRE_PYTHON_VERSION=2.7'
    - env:
      - ARGS=''
      - TAG=inspirehep/elasticsearch:latest
      - DOCKERFILE=elasticsearch/Dockerfile 
 
script:
  - true

deploy:
  provider: script
  script: ./deploy.sh
  on:
    branch: master
