sudo: required
dist: trusty
services:
  - docker

env:
  global:
  - DOCKER_VERSION=1.10.3-0~trusty
  - TAG=temp_tag

before_install:
  # List available docker versions.
  - apt-cache madison docker-engine
  # Update Docker to needed version
  # https:/graysonkoonce.com/managing-docker-and-docker-compose-versions-on-travis-ci/
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y "docker-engine=${DOCKER_VERSION}"

matrix:
  include:
  - env:
    - DOCKER_PROJECT=inspirehep/python-base
    - DOCKER_IMAGE_TAG=2.7
    - DOCKERFILE=python_base/Dockerfile
    - ARGS='--build-arg=INSPIRE_PYTHON_VERSION=2.7'
  - env:
    - DOCKER_PROJECT=inspirehep/python-base
    - DOCKER_IMAGE_TAG=latest
    - DOCKERFILE=python_base/Dockerfile
    - ARGS='--build-arg=INSPIRE_PYTHON_VERSION=2.7'
  - env:
    - DOCKER_PROJECT=inspirehep/elasticsearch
    - DOCKER_IMAGE_TAG=latest
    - DOCKERFILE=elasticsearch/Dockerfile
    - ARGS=''

script:
  - travis_retry docker build -f "$DOCKERFILE" $ARGS -t "$TAG" .
  - chmod +x deploy.sh
  - ./deploy.sh
